version: '3.7'

services:
  sample2:
    build:
      context: .  # Build the HTML page from the Dockerfile in the current directory
    networks:
      - web-network
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "5002"  # Expose port 80 for the NGINX load balancer to access
    deploy:
      replicas: 3  # Scale to 3 replicas of the HTML page service
    environment:
      DB_HOST:  172.17.0.1 # Use master node as the DB host
      DB_PORT: 5432
      DB_DATABASE: coordinator_postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      PGPASSWORD: postgres

  # Citus Worker Nodes (No ports needed)
  worker1:
    image: citusdata/citus:latest
    container_name: citus_worker1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: worker_db1
    command: ["postgres", "-c", "shared_preload_libraries=citus"] 
    networks:
      - web-network

  worker2:
    image: citusdata/citus:latest
    container_name: citus_worker2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: worker_db2
    command: ["postgres", "-c", "shared_preload_libraries=citus"] 
    networks: 
      - web-network
   

  nginx:
    image: nginx:alpine  # Use the official NGINX image
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the custom NGINX config
    ports:
      - "5002:5002"  # Expose port 5003 on the host, forwarding to port 5003 on the container
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
