version: '3.7'

services:
  sample2:
    build:
      context: .
    networks:
      - web-network
    expose:
      - "5002"  # Expose internal port 5002 for sample2
    deploy:
      replicas: 3

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5002:5002"  # Map host port 5002 to NGINX container port 5002
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
